before_script:
  - npm install -g webpack
  - npm install -g gulp
  - npm install

script:
  - npm run lint
  - npm run build

language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
