before_script:
  - npm install -g webpack
  - npm install -g gulp

script:
  - npm build
  - npm test

language: node_js
node_js:
  - "6"
  - "7"
  - "8"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
