language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "node"

script:
  - npm run build:production
  - npm run lint

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
